[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_indexer = "AAwqqwwp4gGzycyh1DpiwvWgGsWyU1CoM5BHJtbd2vet"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/michalrakoczy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
